In [1]:
import pandas as pd 
import numpy as np 
from pathlib import Path
from pycaret.regression import *

In [2]:
data = np.load(Path().resolve().parents[1] / f"data/9chrome_data.npy", allow_pickle=True)[()]
df = pd.DataFrame(data['X'].astype('float64'), columns=data['features'])
df['CT_RT'] = data['y'].astype('float64')
del data

In [4]:
df.to_csv(Path().resolve().parents[1] / "data/chrome.csv")

In [3]:
exp = setup(data = df, 
            target = 'CT_RT', 
            session_id=123,
            normalize = True, 
            transformation = True, 
            #transform_target = True, 
            combine_rare_levels = True, 
            rare_level_threshold = 0.05,
            remove_multicollinearity = True, 
            multicollinearity_threshold = 0.95, 
            #train_size=0.8,
            log_experiment = True, 
            fold=5,
            experiment_name = '9chrome')

In [4]:
compare_models()

ExtraTreesRegressor(bootstrap=False, ccp_alpha=0.0, criterion='mse',
                    max_depth=None, max_features='auto', max_leaf_nodes=None,
                    max_samples=None, min_impurity_decrease=0.0,
                    min_impurity_split=None, min_samples_leaf=1,
                    min_samples_split=2, min_weight_fraction_leaf=0.0,
                    n_estimators=100, n_jobs=-1, oob_score=False,
                    random_state=123, verbose=0, warm_start=False)

In [5]:
ct = create_model('catboost', fold = 5)

In [6]:
tuned_ct = tune_model(ct)

In [7]:
predict_model(tuned_ct)

,Fe,C,Cr,Mn,Si,Ni,Co,Mo,W,Nb,...,Normal,Temper1,AGS No.,CT_Temp,CT_EL,CT_RA,log_CT_CS,log_CT_MCR,CT_RT,Label
0,-1.029508,0.411686,0.560337,1.015361,-1.445352,0.652960,-0.403757,-0.797836,1.273721,-0.022017,...,0.088150,0.177758,-0.581429,1.163347,-0.734136,-0.854391,-1.026196,0.244343,4107.500000,2711.717033
1,1.053935,-0.504832,-0.985890,-1.529638,1.073945,-0.853185,-0.403757,0.943752,-1.011419,1.379526,...,0.088150,1.469816,1.398017,-0.577624,-0.209444,0.746437,0.521789,-0.394251,15761.799805,14075.025808
2,1.053935,-0.504832,-0.985890,-1.529638,1.073945,-0.853185,-0.403757,0.943752,-1.011419,1.379526,...,0.088150,1.469816,1.398017,0.098771,-0.006467,0.005299,-0.441432,-0.568245,18502.400391,22726.490625
3,-1.029508,0.411686,0.560337,1.015361,-1.445352,0.652960,-0.403757,-0.797836,1.273721,-0.022017,...,0.088150,0.177758,-0.581429,2.267060,1.750803,0.561645,-1.956473,0.885817,1043.199951,1028.788807
4,-0.906366,0.705470,0.512300,0.816244,0.201748,0.652960,-0.403757,-0.936363,1.174950,-0.274663,...,0.088150,0.177758,-0.897795,0.098771,-1.278540,-1.532960,-0.317396,-1.227077,33459.898438,42910.579490
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,1.044871,-0.504832,-0.867924,-0.638874,-1.445352,-1.607561,-0.403757,0.910537,-1.011419,1.103408,...,0.503261,-0.272719,0.536270,0.098771,0.481186,1.151637,0.131664,0.961350,895.299988,4825.661297
247,1.227708,0.012406,-1.149014,-0.879179,-1.157421,-1.407515,-0.403757,0.811343,-1.011419,1.379526,...,-0.100465,0.753496,1.331409,0.098771,1.129440,1.151637,0.131664,1.147347,529.000000,4825.661297
248,0.119547,-0.623167,-0.263660,-0.879179,-0.179302,-0.767557,-0.403757,-0.853441,1.044797,0.270344,...,2.582183,0.753496,-0.202655,0.447959,1.129440,0.652575,0.131664,1.077242,490.500000,4825.661297
249,-1.368662,0.012406,1.309595,0.746492,-0.633148,0.523780,-0.403757,-0.908785,1.125134,0.168521,...,0.088150,1.469816,0.480781,0.803178,0.191770,0.306221,0.025315,1.711943,84.599998,1028.788807
250,-0.986113,1.632299,0.718284,0.746492,1.925446,1.795653,2.469795,1.450311,0.334406,-1.455027,...,-0.591081,-1.673166,-1.643076,-0.577624,0.093250,0.076355,1.523903,0.813624,929.200012,1028.788807