In [1]:
import pandas as pd 
import numpy as np 
from pathlib import Path
from pycaret.regression import *

In [4]:
data = np.load(Path().resolve().parents[1] / f"data/aus_data.npy", allow_pickle=True)[()]
df = pd.DataFrame(data['X'].astype('float64'), columns=data['features'])
df['CT_RT'] = data['y'].astype('float64')
del data

In [6]:
df.to_csv(Path().resolve().parents[1] / "data/aus.csv")

In [3]:
exp = setup(data = df, 
            target = 'CT_RT', 
            session_id=123,
            normalize = True, 
            transformation = True, 
            #transform_target = True, 
            combine_rare_levels = True, 
            rare_level_threshold = 0.05,
            remove_multicollinearity = True, 
            multicollinearity_threshold = 0.95, 
            #train_size=0.8,
            log_experiment = True, 
            fold=5,
            experiment_name = 'aus')

In [4]:
compare_models()

ExtraTreesRegressor(bootstrap=False, ccp_alpha=0.0, criterion='mse',
                    max_depth=None, max_features='auto', max_leaf_nodes=None,
                    max_samples=None, min_impurity_decrease=0.0,
                    min_impurity_split=None, min_samples_leaf=1,
                    min_samples_split=2, min_weight_fraction_leaf=0.0,
                    n_estimators=100, n_jobs=-1, oob_score=False,
                    random_state=123, verbose=0, warm_start=False)

In [5]:
ct = create_model('catboost', fold = 5)

In [6]:
tuned_ct = tune_model(ct)

In [7]:
predict_model(tuned_ct)

,C,Cr,Mn,Si,Co,Mo,Nb,P,Cu,Ti,...,B,N,S,AGS No.,CT_Temp,CT_EL,CT_RA,log_CT_CS,CT_RT,Label
0,-2.210903,-1.425674,-1.429766,-1.939183,-0.945170,0.108128,-1.469381,-1.336728,1.503929,1.258959,...,-0.211940,-1.063697,-1.565190,0.975326,0.930476,0.052951,-0.267493,-1.241886,2889.000000,22174.432321
1,1.793959,0.438234,0.196628,-0.485400,-1.819383,-0.762986,1.162289,1.105836,-1.293876,-1.546636,...,-1.416130,-2.246065,-1.565190,2.032121,0.930476,0.961575,1.163163,-0.398283,385.600006,4173.450211
2,-0.686701,-0.194687,0.622673,1.480119,0.411143,-0.446481,0.304834,-0.063834,0.568354,-0.447475,...,-1.019383,0.076407,0.540785,-0.460828,-1.387317,-1.210697,-1.461063,0.297778,25568.400391,40370.275208
3,1.793959,0.438234,0.196628,-0.485400,-1.819383,-0.762986,1.162289,1.105836,-1.293876,-1.546636,...,-1.416130,-2.246065,-1.565190,2.032121,-0.584373,0.558572,0.686125,0.985627,6276.000000,6403.304082
4,-0.472198,0.022580,1.042898,0.660584,0.282596,-0.117400,1.073701,1.306274,1.261157,-0.396671,...,1.049922,0.166542,0.540785,0.296488,-1.387317,-0.407491,0.360700,2.032795,363.600006,-5581.269350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,0.008899,-1.260165,-1.328064,-0.895770,-0.945170,0.478120,-0.923127,-1.522957,-0.801109,1.844025,...,-1.280658,-0.001783,1.495670,1.393985,-1.387317,1.589510,1.062534,1.941503,39.099998,2926.043528
136,0.008899,-1.566252,-1.391201,-0.999076,-1.447807,-0.669716,-1.504588,-1.202039,-1.042619,1.561947,...,0.625984,-1.682426,-1.289720,-2.326754,-1.387317,1.657422,1.556308,0.057142,17416.300781,35308.026575
137,-0.686701,0.244642,0.769023,1.336661,0.561935,-0.277748,0.304834,0.913405,0.568354,-0.346862,...,-0.893675,-0.343730,-0.121339,-1.113986,-1.387317,-1.378518,-1.537699,0.297778,23114.400391,25324.091759
138,-0.686701,-0.194687,0.622673,1.480119,0.411143,-0.446481,0.304834,-0.063834,0.568354,-0.447475,...,-1.019383,0.076407,0.540785,-0.460828,-0.584373,-0.971661,-0.819469,-0.269141,26011.400391,53699.594042
139,-0.686701,-0.194687,0.622673,1.480119,0.411143,-0.446481,0.304834,-0.063834,0.568354,-0.447475,...,-1.019383,0.076407,0.540785,-0.460828,0.555815,-0.472263,-0.501450,0.028995,176.000000,-6302.450743