In [1]:
import pandas as pd 
import numpy as np 
from pathlib import Path
from pycaret.regression import *

In [2]:
data = np.load(Path().resolve().parents[1] / f"data/chrome_data.npy", allow_pickle=True)[()]
df_1 = pd.DataFrame(data['X'].astype('float64'), columns=data['features'])
df_1['CT_RT'] = data['y'].astype('float64')
del data

In [3]:
data = np.load(Path().resolve().parents[1] / f"data/aus_data.npy", allow_pickle=True)[()]
df_2 = pd.DataFrame(data['X'].astype('float64'), columns=data['features'])
df_2['CT_RT'] = data['y'].astype('float64')
del data

In [4]:
df = pd.concat([df_1, df_2])
del df_1, df_2

In [6]:
df.to_csv('/Users/mamu867/PNNL_Mac/PNNL_Code_Base/xmat-pnnl/xmat_pnnl_model/combined/df.csv')

In [6]:
exp = setup(data = df, 
            target = 'CT_RT', 
            session_id=123,
            normalize = True, 
            transformation = True,
            numeric_imputation = 'mean',
            #transform_target = True, 
            combine_rare_levels = True, 
            rare_level_threshold = 0.05,
            remove_multicollinearity = True, 
            multicollinearity_threshold = 0.95, 
            #train_size=0.8,
            log_experiment = True, 
            fold=5,
            experiment_name = 'combined')

In [7]:
compare_models()

ExtraTreesRegressor(bootstrap=False, ccp_alpha=0.0, criterion='mse',
                    max_depth=None, max_features='auto', max_leaf_nodes=None,
                    max_samples=None, min_impurity_decrease=0.0,
                    min_impurity_split=None, min_samples_leaf=1,
                    min_samples_split=2, min_weight_fraction_leaf=0.0,
                    n_estimators=100, n_jobs=-1, oob_score=False,
                    random_state=123, verbose=0, warm_start=False)

In [8]:
ct = create_model('catboost', fold = 5)

In [9]:
tuned_ct = tune_model(ct)

In [10]:
predict_model(tuned_ct)

,C,Cr,Mn,Si,Ni,Co,Mo,W,Nb,Al,...,Temper1_640.0,Temper1_650.0,Temper1_660.0,Temper1_760.0,Temper1_765.0,Temper1_770.0,Temper1_780.0,Temper1_790.0,CT_RT,Label
0,-0.199037,-1.349402,-1.888111,-1.600327,1.995061,-1.789161,-1.056545,-1.068901,-0.874028,2.054660,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26.400000,4210.126634
1,0.026261,0.265308,-0.371479,0.132361,0.116413,0.193795,0.822893,-0.380538,-0.171408,0.290397,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,779.099976,1809.535954
2,0.039212,0.537021,-0.475419,0.046641,0.005797,0.193795,0.134737,1.237683,-0.200027,0.268566,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,65363.398438,63970.194490
3,0.042450,0.396882,-0.407071,-0.020594,0.224327,0.193795,0.253315,1.289300,-0.204075,0.278529,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1983.000000,1472.721238
4,-0.199037,-1.373341,-1.920680,-1.715455,2.148574,-2.453279,-1.295636,-1.068901,-2.089392,0.673454,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,125.500000,2081.159316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386,0.253332,1.357091,0.234148,0.063638,0.801256,0.276735,1.146110,0.863248,-0.320785,0.290397,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2109.100098,958.480066
387,0.854278,-1.208273,0.835199,0.370874,-1.455654,-0.102638,-1.279376,-1.068901,0.694992,-1.251391,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4892.700195,7468.803627
388,-3.283520,-1.362493,-1.939678,-2.676654,2.114268,-1.789161,-1.143006,-1.068901,-1.999748,0.548775,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,58.900002,-801.349707
389,0.058644,1.357091,0.234148,0.012871,0.314892,0.193795,0.103921,1.275483,-0.204075,0.282495,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,51539.000000,59683.705289
390,0.010077,0.221015,-0.219338,0.132361,-0.058632,0.193795,0.812022,-0.380538,-0.183734,0.272559,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,40495.898438,47546.512480

In [11]:
get_config('X_train')

,C,Cr,Mn,Si,Ni,Co,Mo,W,Nb,Al,...,Normal_980.0,Normal_not_available,Temper1_640.0,Temper1_650.0,Temper1_660.0,Temper1_760.0,Temper1_765.0,Temper1_770.0,Temper1_780.0,Temper1_790.0
305,0.058644,0.213272,-0.441713,-0.037210,-0.074873,0.193795,0.844477,-0.380538,-0.183734,0.252484,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
121,-2.263077,-1.226938,1.041403,2.656355,-1.419049,0.165050,-1.263160,-1.068901,1.138778,-1.414825,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
353,-3.283520,-1.362493,-1.939678,-2.676654,2.114268,-1.789161,-1.143006,-1.068901,-1.999748,0.548775,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2.993878,-1.180741,-0.275220,-1.116960,-1.505613,-2.928905,-1.311942,-1.068901,2.056243,-1.787149,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
392,0.042450,0.396882,-0.407071,-0.020594,0.224327,0.193795,0.253315,1.289300,-0.204075,0.278529,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402,-1.339115,-1.393441,-1.869644,-1.541984,2.133018,-2.558031,-1.311126,-1.068901,-2.093195,1.092272,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
311,-0.199037,-1.349402,-1.888111,-1.600327,1.995061,-1.789161,-1.056545,-1.068901,-0.874028,2.054660,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
106,0.042450,0.239168,-0.508200,0.046641,-0.042444,0.193795,0.822893,-0.380538,-0.228148,0.282495,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
205,-1.236042,-1.205146,1.149415,2.090198,-1.415394,0.400444,-1.222822,-1.068901,0.955512,-1.669947,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
286,-0.199037,-1.219959,2.138377,-0.138222,-1.427824,-0.174592,-1.158877,-1.068901,1.946918,-1.583583,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0